<a href="https://colab.research.google.com/github/urenajose/DS-Unit-1-Sprint-3-Linear-Algebra/blob/master/Jose_DS_132_Intermediate_Linear_Algebra_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Statistics

## 1.1 Sales for the past week was the following amounts: [3505, 2400, 3027, 2798, 3700, 3250, 2689]. Without using library functions, what is the mean, variance, and standard deviation of of sales from last week? (for extra bonus points, write your own function that can calculate these two values for any sized list)

In [1]:
mean_of_sales = (3505+2400+3027+2798+3700+3250+2689)/7
mean_of_sales

3052.714285714286

## 1.2 Find the covariance between last week's sales numbers and the number of customers that entered the store last week: [127, 80, 105, 92, 120, 115, 93] (you may use librray functions for calculating the covariance since we didn't specifically talk about its formula)

In [2]:
import pandas as pd
Store = pd.DataFrame({"customers_number":[127, 80, 105, 92, 120, 115, 93], "Sales":[3505, 2400, 3027, 2798, 3700, 3250, 2689]})
Store.head()
Store.cov()

customers_number          Sales
customers_number        290.952381    7604.357143
Sales                  7604.357143  214387.904762

## 1.3 Find the standard deviation of customers who entered the store last week. Then, use the standard deviations of both sales and customers to standardize the covariance to find the correlation coefficient that summarizes the relationship between sales and customers. (You may use library functions to check your work.)

Standard deviation of customers who entered the store last week

In [3]:
import math
Mean_customers = (127+ 80+ 105+ 92+ 120+ 115+ 93)/7
print("Mean_customers",Mean_customers)
Variance_customers = ((127-Mean_customers)**2+ (80-Mean_customers)**2+ (105-Mean_customers)**2+ (92-Mean_customers)**2+ (120-Mean_customers)**2+ (115-Mean_customers)**2+ (93-Mean_customers)**2)/7
print("Variance", Variance_customers)
std_customers = math.sqrt(Variance_customers)
print("std",std_customers)
Variance_customers**(1/2) #another way to get the square root without importing math.
print("pd.std population",Store["customers_number"].std(ddof=0)) #ddof=0 to us population
print("pd.std sample",Store["customers_number"].std(ddof=1)) #pandas by default assumes sample poputlation

Mean_customers 104.57142857142857
Variance 249.3877551020408
std 15.792015549069118
pd.std population 15.792015549069118
pd.std sample 17.057326313123664


##"Pearson's Correlation" ![image.png](https://www.mathsisfun.com/data/images/correlation-formula.gif)

In [4]:
#Step 1: Find the mean of x, and the mean of y
#Step 2: Subtract the mean of x from every x value, and subtract the mean of y from every y value
sales_a = [(3505-mean_of_sales), (2400-mean_of_sales), (3027-mean_of_sales), (2798-mean_of_sales), (3700-mean_of_sales), (3250-mean_of_sales), (2689-mean_of_sales)]
customers_b = [(127-Mean_customers), (80-Mean_customers), (105-Mean_customers), (92-Mean_customers), (120-Mean_customers), (115-Mean_customers), (93-Mean_customers)]
print(sales_a)
print(customers_b)


[452.2857142857142, -652.7142857142858, -25.71428571428578, -254.71428571428578, 647.2857142857142, 197.28571428571422, -363.7142857142858]
[22.42857142857143, -24.57142857142857, 0.4285714285714306, -12.57142857142857, 15.42857142857143, 10.42857142857143, -11.57142857142857]


In [5]:
#Step 3: Calculate: ab, a2 and b2 for every value
ab_customers_sales = ((sales_a[0]*customers_b[0])+(sales_a[1]*customers_b[1])+(sales_a[2]*customers_b[2])+(sales_a[3]
                      *customers_b[3])+(sales_a[4]*customers_b[4])+(sales_a[5]*customers_b[5])+(sales_a[6]*customers_b[6]))#ab
print(ab_customers_sales)

45626.142857142855


In [6]:
customers_b2 = ((127-Mean_customers)**2+ (80-Mean_customers)**2+ (105-Mean_customers)**2+ (92-Mean_customers)**2+ (120-Mean_customers)**2+ (115-Mean_customers)**2+ (93-Mean_customers)**2)
sales_a2 = ((3505-mean_of_sales)**2+ (2400-mean_of_sales)**2+ (3027-mean_of_sales)**2+ (2798-mean_of_sales)**2+ (3700-mean_of_sales)**2+ (3250-mean_of_sales)**2+ (2689-mean_of_sales)**2)
Rxy = ab_customers_sales/(sales_a2*customers_b2)**(1/2) #ab/sqrt(sum a2*sum b2) **(1/2) = math.sqrt()
print("correlation coefficient sales and customers =",  round(Rxy,2))
print("pandas correlation coefficient  sales and customers =",  Store["customers_number"].corr(Store["Sales"]))
print("\n pandas correlation sales and customers \n",  Store.corr())

correlation coefficient sales and customers = 0.96
pandas correlation coefficient  sales and customers = 0.9628339778148909

 pandas correlation sales and customers 
                   customers_number     Sales
customers_number          1.000000  0.962834
Sales                     0.962834  1.000000


In [7]:
import numpy as np
Rxy_np = np.corrcoef(Store["customers_number"], Store["Sales"])
print(Rxy_np)
print("numpy correlation sales and customers =", Rxy_np[0,1])

[[1.         0.96283398]
 [0.96283398 1.        ]]
numpy correlation sales and customers = 0.9628339778148909


## 1.4 Use pandas to import a cleaned version of the titanic dataset from the following link: [Titanic Dataset](https://raw.githubusercontent.com/Geoyi/Cleaning-Titanic-Data/master/titanic_clean.csv)

## Calculate the variance-covariance matrix and correlation matrix for the titanic dataset's numeric columns. (you can encode some of the categorical variables and include them as a stretch goal if you finish early)

# Orthogonality

## 2.1 Plot two vectors that are orthogonal to each other. What is a synonym for orthogonal?

In [8]:
j = np.random.randn(3) #take a random vector
print(j)
o = np.random.randn(3)  # take a random vector
print(o)
o -= o.dot(j) * j  / np.linalg.norm(j)**2    # make it orthogonal to j
print(o)
#x /= np.linalg.norm(x)  # normalize it


#y = np.cross(k, x)      # cross product with k

print("j.o",np.dot(j,o))

[0.29781674 0.9423214  0.11402749]
[ 0.49802596 -1.051127   -0.56146182]
[ 0.7707257  -0.18827825 -0.45705107]
j.o -1.3183898417423734e-16


## 2.2 Are the following vectors orthogonal? Why or why not?

\begin{align}
a = \begin{bmatrix} -5 \\ 3 \\ 7 \end{bmatrix}
\qquad
b = \begin{bmatrix} 6 \\ -8 \\ 2 \end{bmatrix}
\end{align}

In [9]:
a = np.array([-5,3,7])
print(a)
b = np.array([6,-8,2])
print("\n",b)
print("Not Orthogonal, dot product is not equal to zero",np.dot(a,b))

[-5  3  7]

 [ 6 -8  2]
Not Orthogonal, dot product is not equal to zero -40


## 2.3 Compute the following values: What do these quantities have in common?

## What is $||c||^2$? 

## What is $c \cdot c$? 

## What is $c^{T}c$?

\begin{align}
c = \begin{bmatrix} 2 & -15 & 6 & 20 \end{bmatrix}
\end{align}

In [27]:
c = np.array([2,-15,6,20])
ct = np.array([[2,-15,6,20]])
print("\u2016c\u20162 is Norm square",np.linalg.norm(c)**2)
print("c dot c product", np.dot(c,c))
print(c)
print(c.T)
print(ct.T)
print("C transpose time C", (ct@c))

‖c‖2 is Norm square 665.0
c dot c product 665
[  2 -15   6  20]
[  2 -15   6  20]
[[  2]
 [-15]
 [  6]
 [ 20]]
C transpose time C [665]


# Unit Vectors

## 3.1 Using Latex, write the following vectors as a linear combination of scalars and unit vectors:

\begin{align}
d = \begin{bmatrix} 7 \\ 12 \end{bmatrix}
\qquad
e = \begin{bmatrix} 2 \\ 11 \\ -8  \end{bmatrix}
\end{align}

Your text here

## 3.2 Turn vector $f$ into a unit vector:

\begin{align}
f = \begin{bmatrix} 4 & 12 & 11 & 9 & 2 \end{bmatrix}
\end{align}

# Linear Independence / Dependence 

## 4.1 Plot two vectors that are linearly dependent and two vectors that are linearly independent (bonus points if done in $\mathbb{R}^3$).

# Span

## 5.1 What is the span of the following vectors?

\begin{align}
g = \begin{bmatrix} 1 & 2 \end{bmatrix}
\qquad
h = \begin{bmatrix} 4 & 8 \end{bmatrix}
\end{align}

## 5.2 What is the span of $\{l, m, n\}$?

\begin{align}
l = \begin{bmatrix} 1 & 2 & 3 \end{bmatrix}
\qquad
m = \begin{bmatrix} -1 & 0 & 7 \end{bmatrix}
\qquad
n = \begin{bmatrix} 4 & 8  & 2\end{bmatrix}
\end{align}

# Basis

## 6.1 Graph two vectors that form a basis for $\mathbb{R}^2$



## 6.2 What does it mean to form a basis?

# Rank

## 7.1 What is the Rank of P?

\begin{align}
P = \begin{bmatrix} 
1 & 2 & 3 \\
 -1 & 0 & 7 \\
4 & 8  & 2
\end{bmatrix}
\end{align}

## 7.2 What does the rank of a matrix tell us?

# Linear Projections

## 8.1 Line $L$ is formed by all of the vectors that can be created by scaling vector $v$ 
\begin{align}
v = \begin{bmatrix} 1 & 3 \end{bmatrix}
\end{align}

\begin{align}
w = \begin{bmatrix} -1 & 2 \end{bmatrix}
\end{align}

## find $proj_{L}(w)$

## graph your projected vector to check your work (make sure your axis are square/even)

# Stretch Goal

## For vectors that begin at the origin, the coordinates of where the vector ends can be interpreted as regular data points. (See 3Blue1Brown videos about Spans, Basis, etc.)

## Write a function that can calculate the linear projection of each point (x,y) (vector) onto the line y=x. run the function and plot the original points in blue and the new projected points on the line y=x in red. 

## For extra points plot the orthogonal vectors as a dashed line from the original blue points to the projected red points.

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

# Creating a dataframe for you to work with -Feel free to not use the dataframe if you don't want to.
x_values = [1, 4, 7, 3, 9, 4, 5 ]
y_values = [4, 2, 5, 0, 8, 2, 8]

data = {"x": x_values, "y": y_values}

df = pd.DataFrame(data)

df.head()

plt.scatter(df.x, df.y)
plt.show()